### ISSUE TITLE
PostgreSQL 9.3 column prokind doesn't exist when attempting to view functions.

### ISSUE THREAD

**Issue by jobe1986** [phppgadmin/phppgadmin#101]
The error that occurs when attempting to view/list functions is:
`ERROR:  column p.prokind does not exist`

Basically as of postgresql 9.3 the pg_proc field prokind does not exist as that was added much later. Therefore allowances need to be made for this as the change to prokind did not happen until version 11, therefore all versions prior to version 11 need to continue to using the old method that did not use the prokind field. That includes versions 9.0 to 9.6 and 10.

**Comment by xzilla** [comment]
I would note that 9.3 isn't really supported any more, but still I believe this issue was resolved in this commit: https://github.com/phppgadmin/phppgadmin/commit/e3e8087bfd8f1fb93564b7a691f8ac9ed7c63a02. If you are still having issues, please re-open this issue and include your phppgadmin version and postgres version and steps to reproduce.

**Comment by jobe1986** [comment]
Nope, that commit doesn;t fix the issue. The issue in hand is that the change of column was made to the base Postgres class that Postgres93 inherits (indirectly from the Postgres94 class), despite the fact the change to PostgreSQL's own data structure doesnt make that change until version 11, which is the first point at which the column prokind should be used and no earlier.

To elaborate, classes/database/Postgres93.php inherits the class from classes/database/Postgres94.php which inherits the class from classes/database/Postgres.php where you can see several uses of the "prokind" column which doesnt exist for 9.3 or 9.4.

The exact error as presented is:
SQL error:
```
ERROR:  column p.prokind does not exist
LINE 14:     CASE p.prokind
                  ^
In statement:

			SELECT
				
				p.oid AS prooid,
				p.proname,
				p.proretset,
				pg_catalog.format_type(p.prorettype, NULL) AS proresult,
				pg_catalog.oidvectortypes(p.proargtypes) AS proarguments,
				pl.lanname AS prolanguage,
				pg_catalog.obj_description(p.oid, 'pg_proc') AS procomment,
				p.proname || ' (' || pg_catalog.oidvectortypes(p.proargtypes) || ')' AS proproto,
				CASE WHEN p.proretset THEN 'setof ' ELSE '' END || pg_catalog.format_type(p.prorettype, NULL) AS proreturns,
				u.usename AS proowner,
				CASE p.prokind
  					WHEN 'a' THEN 'agg'
  					WHEN 'w' THEN 'window'
  					WHEN 'p' THEN 'proc'
  					ELSE 'func'
 				END as protype
			FROM pg_catalog.pg_proc p
				INNER JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
				INNER JOIN pg_catalog.pg_language pl ON pl.oid = p.prolang
				LEFT JOIN pg_catalog.pg_user u ON u.usesysid = p.proowner
			WHERE NOT p.prokind = 'a' 
				AND n.nspname = 'http'
			ORDER BY p.proname, proresult
```

**Comment by arekm** [comment]
(https://github.com/phppgadmin/phppgadmin/commit/f3171e923185c3add7c080ec0690233267c220f6) fixed it for me on older postgres (7.x)
