### ISSUE TITLE
pg_catalog.pg_proc.prokind Missing in Older PostgreSQL

### ISSUE THREAD

**Issue by rsecor** [phppgadmin/phppgadmin#105]
I found a reference to a change to prokind from "proisagg"
"Replace system catalog pg_proc 's proisagg and proiswindow columns with prokind (Peter Eisentraut)."

Currently using PostgreSQL 9.2.24 (working on updating out of it but there are still oid's in use.)

**Comment by rsecor** [comment]
Temporary fix was to copy getFunctions in Postgres.php from phppgadmin 5.6 and put it in Postgre92.php

**Comment by xzilla** [comment]
I'd be interested in a link to that reference if you have one. That sounds like the changes we made for Postgres 11 (https://github.com/phppgadmin/phppgadmin/commit/e3e8087bfd8f1fb93564b7a691f8ac9ed7c63a02) although that should have been backwards compatible... does your function definition match the one in that commit that is in Postgres10.php? 

FWIW your fix should work for you, just wondering if there needs to be something more done and/or if the fix might go some place better for newer versions... I don't think any of it has been tested on versions older than 9.5

**Comment by rsecor** [comment]
It looks like the function for getFunctions I put in Postgres92.php is the same as the one in Postgre10.php.

 https://youtrack.jetbrains.com/issue/DBE-6818

https://www.postgresql.org/docs/11/release-11.htm stats "Replace system catalog pg_proc's proisagg and proiswindow columns with prokind (Peter Eisentraut)
This new column more clearly distinguishes functions, procedures, aggregates, and window functions."

**Comment by xzilla** [comment]
Ok, I believe this is fixed in the current release then. Thanks for the report.
