### ISSUE TITLE
Postgresql 13 Released Changes Needed

### ISSUE THREAD

**Issue by rsecor** [phppgadmin/phppgadmin#107]
Just did a major upgrade from Postgres 9.2 to Postgres 13...

Needed to update ./classes/database/Connection.php to include Postgres13

My changes/additions:
            case '12': return 'Postgres12';break;
            case '13': return 'Postgres13';break;

Added:
     ./classes/database/Postgres12.php
     ./classes/database/Postgres13.php
     ./help/PostgresDoc13.php

I believe this takes care of what I need to get Postgres13 to work.

**Comment by xzilla** [comment]
Ah, interesting, thanks for the information. Any chance you want to put a PR together?
