### ISSUE TITLE
postgresqlMinVer undefined in misc.php

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [phppgadmin/phppgadmin#109]
last git:
Notice: Undefined variable: postgresqlMinVer in phpPgAdmin/classes/Misc.php on line 493
Version of PostgreSQL not supported. Please upgrade to version or later.
I use postgresql-13.0 thanks

**Comment by xzilla** [comment]
I'm planning to merge this today, but maybe you want a sneak peak of https://github.com/phppgadmin/phppgadmin/pull/108 ?

**Comment by ROBERT-MCDOWELL** [comment]
no worry ;), I just saw that this var is set in lib.inc but no include of it from misc.php.
anyhow it's obviously targeted the condiction that didn't recognized pgsql version 13.
will git pull later thanks

**Comment by xzilla** [comment]
I release 7.13.0 today which includes support for Postgres 13, if you find any issues, please open up a new ticket.

**Comment by VarunHeyLog** [comment]
Issue is back again :/

**Comment by haikarainen** [comment]
Get this on Ubuntu 20.04 package

**Comment by robertsasik** [comment]
Hello, The issue Warning: Undefined variable $postgresqlMinVer... is back.
I have the version of PostgreSQL 15.
