### ISSUE TITLE
Create button is missing in database creation form in phpmyadmin

### ISSUE THREAD

**Issue by hmalindu1** [phppgadmin/phppgadmin#136]
![image](https://user-images.githubusercontent.com/80053647/109985065-61552300-7d2a-11eb-93f5-8a9901a8fcb1.png)

at the very first I got the error message below.
![image](https://user-images.githubusercontent.com/80053647/109985208-877ac300-7d2a-11eb-8b88-03caae8967b0.png)

Then I solved it by commenting out this part below
![image](https://user-images.githubusercontent.com/80053647/109985320-a37e6480-7d2a-11eb-817e-98c31aaca11f.png)

Then when I try to create a database, the create button is missing as shown above. 
I am newbie for programming.

**Comment by hmalindu1** [comment]
![image](https://user-images.githubusercontent.com/80053647/109985589-efc9a480-7d2a-11eb-8402-c49f7012869e.png)

**Comment by ormorph** [comment]
[Patch](https://github.com/phppgadmin/phppgadmin/files/6102678/phpPgAdmin-7.13.0-php8.patch.gz)

**Comment by hmalindu1** [comment]
> 
> 
> [Patch](https://github.com/phppgadmin/phppgadmin/files/6102678/phpPgAdmin-7.13.0-php8.patch.gz)

**Comment by hmalindu1** [comment]
> 
> 
> [Patch](https://github.com/phppgadmin/phppgadmin/files/6102678/phpPgAdmin-7.13.0-php8.patch.gz)

Hi, I am a newbie. What should I do with this zip file. Thanks

**Comment by ormorph** [comment]
>Hi, I am a newbie. What should I do with this zip file. Thanks

```
$ wget https://github.com/phppgadmin/phppgadmin/releases/download/REL_7-13-0/phpPgAdmin-7.13.0.tar.bz2
$ tar xjf phpPgAdmin-7.13.0.tar.bz2 
$ cd phpPgAdmin-7.13.0
$ wget https://github.com/phppgadmin/phppgadmin/files/6102678/phpPgAdmin-7.13.0-php8.patch.gz
$ zcat phpPgAdmin-7.13.0-php8.patch.gz | patch -Np1
```
Change the line in your `conf/config.inc.php` file to this:
```
$conf['extra_login_security'] = false;
```
Then you can run:
```
$ php -S localhost:4000
```
Something like this.

**Comment by ormorph** [comment]
Most likely something was done wrong. If the patch is not installed, it will not work.
I don't know what OS you are using, but I tested it on gentoo with php8.
If the patch was not installed, then you could not enter the database, despite this line.

**Comment by hmalindu1** [comment]
I am using windows 10. Is there something to do with the os?

**Comment by ormorph** [comment]
If it is still not clear what to edit, I attach an archive with the changed files, you can simply copy them into the source code. There are only two files in the archive.
[phpPgAdmin-7.13.0.tar.gz](https://github.com/phppgadmin/phppgadmin/files/6109173/phpPgAdmin-7.13.0.tar.gz)
