### ISSUE TITLE
phpPgAdmin-7.12.0.tar.bz2 flaw (trailing garbage after EOF)

### ISSUE THREAD

**Issue by jschleus** [phppgadmin/phppgadmin#66]
On my Linux system an integrity check via the command
`
bzip2 -t phpPgAdmin-7.12.0.tar.bz2
`
issues
`
trailing garbage after EOF ignored
`

**Comment by xzilla** [comment]
Can you check out the download for 5.6 and verify if the same problem exists for you there?

**Comment by jschleus** [comment]
Yes, the same problem.

But I should mention that the contents of phpPgAdmin-7.12.0.tar.bz2 seems identical to the phpPgAdmin-7.12.0.zip archive that expands without any errors. Only a self-written extracting wrapper script  "stumbled" about the mentioned output message.

**Comment by xzilla** [comment]
This seems like it isn't a serious issue, thought it'd be nice to clean it up if we could. It seems to stem from how the code is pulled from github (via git archive command). I've uploaded a copy of the release.sh script that I use to build the releases. Note I am using OSX, although I don't think that matters.

**Comment by jschleus** [comment]
I agree that it isn't a serious issue. Just for curiosity I just made a hex dump of the tarball
and saw at the end many NUL bytes (may be they are used to fill a given block size?).

By the way, after a
```bunzip2 phpPgAdmin-7.12.0.tar.bz2```
and a following
```bzip2 --best phpPgAdmin-7.12.0.test.tar```
the hex dump of the new generated tarball is principally identical but the trailing garbage of the NUL bytes is vanished and `bzip2 -t phpPgAdmin-7.12.0.tar.bz2` is now longer claiming.

**Comment by nirgal** [comment]
@xzilla where is that release.sh ? I can't find it in master ...

**Comment by jschleus** [comment]
I don't know what is meant by release.sh. But I found a typo in my comment above: Naturally  the compression command was (without ".test")
```
bzip2 --best phpPgAdmin-7.12.0.tar
```
Maybe it's related.

**Comment by xzilla** [comment]
Awesome. This fixes the issue for me, so I've pushed this into the release script, you can find the commit at https://github.com/phppgadmin/project/commit/d95a9ec40b6236349fb868f32d0680467e7adb4c

I'm going to leave the existing tarballs as is, as I hope to have a new release in the next week or so. Thanks again for finding the issue and the suggested fix.
