### ISSUE TITLE
Function hasObjectID queries non-existent column relhasoids on PG12

### ISSUE THREAD

**Issue by petrcech** [phppgadmin/phppgadmin#67]
Unable to browse DB upgraded to 12rc1 with following error

ERROR:  column "relhasoids" does not exist
LINE 1: SELECT relhasoids FROM pg_catalog.pg_class WHERE relname='bs...

regards
Petr

**Comment by horaciod** [comment]
changing the function hasObjectID on 
classes/database/Postgres.php 
from 
$sql = "SELECT   **relhasoids**   FROM pg_catalog.pg_class WHERE relname='{$table}'
			AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname='{$c_schema}')";
to 
$sql = "SELECT **oid as relhasoids**   FROM pg_catalog.pg_class WHERE relname='{$table}'
			AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname='{$c_schema}')";
solve the problem with PostgreSQL 12.0 (Debian 12.0-1.pgdg100+1)

**Comment by nirgal** [comment]
Well, actually, no!

The whole point of the function hasObjectID() is to know whether the hidden columns "oid" should be explicitly requested in queries.
But [that feature is gone](https://www.postgresql.org/docs/12/release-12.html#id-1.11.6.5.4) with postgres 12.

So the function should probably always return false, and the code moved in an overwritten version in Postgres11.php

**Comment by xzilla** [comment]
This is now fixed in git, and will be released shortly. Thank you for your report!
