### ISSUE TITLE
composer.json should document the dependency on pgsql

### ISSUE THREAD

**Issue by nirgal** [phppgadmin/phppgadmin#71]
The composer file is a bit outdated.

The minimal php version there is 5.0 while ``libraries/lib.inc.php`` will complain if version is less than 7.1. The value should be ajusted.

Also it should contain a ``require`` line like ``"ext-pgsql": "*"`` so that extension php-pgsql is pulled automatically.

**Comment by xzilla** [comment]
Fixed.
