### ISSUE TITLE
Create table with oids fails on PG12

### ISSUE THREAD

**Issue by nirgal** [phppgadmin/phppgadmin#80]
oid special behavior has been removed in postgres 12.
https://www.postgresql.org/docs/12/release-12.html#id-1.11.6.5.4

This explains #67.

Another issue is is creating a table unchecking the "WITHOUT OIDS" box:
This results in a SQL error:
```
ERROR:  syntax error at or near "OIDS"
CREATE TABLE "public"."test_to_drop" ("id" SERIAL, "test" character varying(20)) WITH OIDS
                                                                                      ^
```

I guess the checkbox should be removed when talking to a postgres 12.

**Comment by xzilla** [comment]
This is now fixed in git, and will be released shortly. Thanks for your report!
