### ISSUE TITLE
column "relhasoids" does not exist

### ISSUE THREAD

**Issue by malohtie** [phppgadmin/phppgadmin#83]
hi
i'm using the last release with postgres 12.1

![image](https://user-images.githubusercontent.com/20033279/69000639-157f3000-08d3-11ea-9672-c569a2298120.png)

this happen when i parcour something

**Comment by sanzstez** [comment]
+1

**Comment by xzilla** [comment]
This is fixed in git master and will be released shortly. Thank you for your report.
