### ISSUE TITLE
Does Phppgadmin 5 version supports pgadmin 10?

### ISSUE THREAD

**Issue by asprabhu83** [phppgadmin/phppgadmin#97]
Does Phppgadmin 5 version supports pgadmin 10?

**Comment by asprabhu83** [comment]
Getting error on all_db.php while loading. This doesnt happen frequently, but rarely.

**Comment by xzilla** [comment]
I would expect 5.6 to have worked with postgres 10. That said, 5.6 is EOL, and you should probably upgrade to 7.12.1
