### ISSUE TITLE
phpPgAdmin 7.12.1 Certificate auth

### ISSUE THREAD

**Issue by fuogo** [phppgadmin/phppgadmin#98]
Connect to  Google Cloud SQL , sslmode = verify-ca 
sslrootcert=server-ca.pem
sslcert=client-cert.pem
sslkey=client-key.pem

What should I do, thank you! #

**Comment by xzilla** [comment]
Sorry, but the issue tracker is for bug/features/issues within the software itself, and not a support forum.
